export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const INCREASE_ITEM="INCREASE_ITEM"
export const DECREASE_ITEM="DECREASE_ITEM"
export const ADD_TO_FAVORITES="ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES="ADD_FROM_FAVORITES"
export const ADD_TO_PRODUCTDETAIL="ADD_TO_PRODUCTDETAIL"
export const INCREASE_PRODUCTDETAIL="INCREASE_PRODUCTDETAIL"
export const DECREASE_PRODUCTDETAIL="DECREASE_PRODUCTDETAIL"



