import {s} from 'react-native-size-matters';
export const fonts = {
  interBlack: 'Inter-Black',
  interBlackItalic: 'Inter-BlackItalic',
  interBold: 'Inter-Bold',
  interBoldItalic: 'Inter-BoldItalic',
  interExtraBold: 'Inter-ExtraBold',
  interExtraBoldItalic: 'Inter-ExtraBoldItalic',
  interExtraLight: 'Inter-ExtraLight',
  interExtraLightItalic: 'Inter-ExtraLightItalic',
  interItalic: 'Inter-Italic',
  interLight: 'Inter-Light',
  interLightItalic: 'Inter-LightItalic',
  interMedium: 'Inter-Medium',
  interMediumItalic: 'Inter-MediumItalic',
  interRegular: 'Inter-Regular',
  interSemiBold: 'Inter-SemiBold',
  interSemiBoldItalic: 'Inter-SemiBoldItalic',
  interThin: 'Inter-Thin',
  interThinItalic: 'Inter-ThinItalic',
  poppinsBlack: 'Poppins-Black',
  poppinsBlackItalic: 'Poppins-BlackItalic',
  poppinsBold: 'Poppins-Bold',
  poppinsBoldItalic: 'Poppins-BoldItalic',
  poppinsExtraBold: 'Poppins-ExtraBold',
  poppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  poppinsExtraLight: 'Poppins-ExtraLight',
  poppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
  poppinsItalic: 'Poppins-Italic',
  poppinsLight: 'Poppins-Light',
  poppinsLightItalic: 'Poppins-LightItalic',
  poppinsMedium: 'Poppins-Medium',
  poppinsMediumItalic: 'Poppins-MediumItalic',
  poppinsRegular: 'Poppins-Regular',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  poppinsThin: 'Poppins-Thin',
  poppinsThinItalic: 'Poppins-ThinItalic',
};

export const fontSize = {
  s: s(10),
  m: s(12),
  l: s(14),
  xl: s(16),
  xxl: s(18),
  xxxl: s(20),
  xxxxl: s(24),
};
